-- 초기 스키마: products, orders, configs 기본 테이블
-- (이미 DB에 적용되어 있는 경우 IF NOT EXISTS로 안전하게 실행 가능)

-- configs 테이블
CREATE TABLE IF NOT EXISTS configs (
  id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  key   TEXT UNIQUE NOT NULL,
  value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- products 테이블
CREATE TABLE IF NOT EXISTS products (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name           TEXT NOT NULL,
  price          INTEGER NOT NULL DEFAULT 0,
  description    TEXT,
  options        TEXT,
  image_url      TEXT,
  image_urls     TEXT[],
  category_id    INTEGER,
  stock          INTEGER NOT NULL DEFAULT 0,
  is_out_of_stock BOOLEAN DEFAULT false,
  is_live        BOOLEAN DEFAULT false,
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_live ON products(is_live);

-- categories 테이블
CREATE TABLE IF NOT EXISTS categories (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name       TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- orders 테이블
CREATE TABLE IF NOT EXISTS orders (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_name    TEXT NOT NULL,
  customer_phone   TEXT NOT NULL,
  address          TEXT,
  detail_address   TEXT,
  zonecode         TEXT,
  product_id       INTEGER REFERENCES products(id) ON DELETE SET NULL,
  product_name     TEXT NOT NULL,
  price            INTEGER,
  options          TEXT,
  payment_method   TEXT DEFAULT 'bank_transfer',
  quantity         INTEGER NOT NULL DEFAULT 1,
  selected_option  TEXT,
  deposit_name     TEXT,
  requests         TEXT,
  status           TEXT NOT NULL DEFAULT '미입금',
  tracking_number  TEXT,
  carrier          TEXT,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_product_id ON orders(product_id);
