-- 쿠폰 테이블 생성
CREATE TABLE IF NOT EXISTS coupons (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  discount_value INTEGER NOT NULL,
  min_purchase INTEGER DEFAULT 0,
  max_discount INTEGER,
  usage_limit INTEGER,
  used_count INTEGER DEFAULT 0,
  valid_from TIMESTAMP WITH TIME ZONE,
  valid_until TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 쿠폰 사용 내역 테이블
CREATE TABLE IF NOT EXISTS coupon_usages (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  coupon_id INTEGER REFERENCES coupons(id) ON DELETE CASCADE,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  customer_phone TEXT,
  discount_amount INTEGER NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons(code);
CREATE INDEX IF NOT EXISTS idx_coupons_active ON coupons(is_active);
CREATE INDEX IF NOT EXISTS idx_coupon_usages_coupon ON coupon_usages(coupon_id);
CREATE INDEX IF NOT EXISTS idx_coupon_usages_order ON coupon_usages(order_id);
CREATE INDEX IF NOT EXISTS idx_coupon_usages_phone ON coupon_usages(customer_phone);

-- 쿠폰 사용 횟수 증가 RPC 함수
CREATE OR REPLACE FUNCTION increment_coupon_usage(coupon_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE coupons
  SET used_count = used_count + 1,
      updated_at = NOW()
  WHERE id = coupon_id;
END;
$$;
