-- 장바구니 테이블 생성
CREATE TABLE IF NOT EXISTS cart (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_phone TEXT NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,
  selected_option TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_cart_customer_phone ON cart(customer_phone);
CREATE INDEX IF NOT EXISTS idx_cart_product_id ON cart(product_id);
CREATE INDEX IF NOT EXISTS idx_cart_customer_product ON cart(customer_phone, product_id);
