-- 도파밍 요소 (선참순, 추첨, 한정판) 테이블 생성

-- 1. products 테이블에 도파밍 관련 필드 추가
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_limited BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS limited_quantity INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS flash_sale_enabled BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS flash_sale_start_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS flash_sale_end_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS flash_sale_quantity INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS flash_sale_sold_quantity INTEGER DEFAULT 0;

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_products_flash_sale ON products(flash_sale_enabled, flash_sale_start_time, flash_sale_end_time);
CREATE INDEX IF NOT EXISTS idx_products_limited ON products(is_limited);

-- 2. 선참순 판매 기록 테이블
CREATE TABLE IF NOT EXISTS flash_sales (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  customer_phone TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  purchased_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_flash_sales_product ON flash_sales(product_id);
CREATE INDEX IF NOT EXISTS idx_flash_sales_customer ON flash_sales(customer_phone);
CREATE INDEX IF NOT EXISTS idx_flash_sales_purchased_at ON flash_sales(purchased_at);

-- 3. 추첨 이벤트 테이블
CREATE TABLE IF NOT EXISTS raffles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  max_participants INTEGER,
  winner_count INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN DEFAULT true,
  is_completed BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_raffles_product ON raffles(product_id);
CREATE INDEX IF NOT EXISTS idx_raffles_active ON raffles(is_active, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_raffles_completed ON raffles(is_completed);

-- 3. 추첨 참여 테이블
CREATE TABLE IF NOT EXISTS raffle_entries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  raffle_id INTEGER REFERENCES raffles(id) ON DELETE CASCADE,
  customer_phone TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  entered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_winner BOOLEAN DEFAULT false
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_raffle_entries_raffle ON raffle_entries(raffle_id);
CREATE INDEX IF NOT EXISTS idx_raffle_entries_customer ON raffle_entries(customer_phone);
CREATE INDEX IF NOT EXISTS idx_raffle_entries_winner ON raffle_entries(is_winner);

-- 4. 추첨 당첨자 테이블 (별도 관리를 위한 테이블)
CREATE TABLE IF NOT EXISTS raffle_winners (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  raffle_id INTEGER REFERENCES raffles(id) ON DELETE CASCADE,
  customer_phone TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  won_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_raffle_winners_raffle ON raffle_winners(raffle_id);
CREATE INDEX IF NOT EXISTS idx_raffle_winners_customer ON raffle_winners(customer_phone);

-- 5. 선참순 판매 수량 증가 RPC 함수
CREATE OR REPLACE FUNCTION increment_flash_sale_sold(product_id INTEGER, quantity INTEGER DEFAULT 1)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE products
  SET flash_sale_sold_quantity = flash_sale_sold_quantity + quantity
  WHERE id = product_id;
END;
$$;

-- 6. 선참순 판매 가능 여부 확인 RPC 함수
CREATE OR REPLACE FUNCTION check_flash_sale_availability(product_id INTEGER)
RETURNS TABLE(
  is_available BOOLEAN,
  remaining_quantity INTEGER,
  is_active BOOLEAN,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    (p.flash_sale_enabled = true
     AND p.flash_sale_quantity > p.flash_sale_sold_quantity
     AND p.flash_sale_start_time <= NOW()
     AND p.flash_sale_end_time >= NOW()) as is_available,
    (p.flash_sale_quantity - p.flash_sale_sold_quantity) as remaining_quantity,
    p.flash_sale_enabled as is_active,
    p.flash_sale_start_time,
    p.flash_sale_end_time
  FROM products p
  WHERE p.id = product_id;
END;
$$;

-- 7. 추첨 참여 가능 여부 확인 RPC 함수
CREATE OR REPLACE FUNCTION check_raffle_availability(raffle_id INTEGER, customer_phone TEXT)
RETURNS TABLE(
  is_available BOOLEAN,
  already_entered BOOLEAN,
  current_participants INTEGER,
  max_participants INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
  entry_count INTEGER;
BEGIN
  -- 이미 참여했는지 확인
  SELECT COUNT(*) INTO entry_count
  FROM raffle_entries
  WHERE raffle_id = raffle_id AND customer_phone = customer_phone;

  RETURN QUERY
  SELECT
    (r.is_active = true
     AND r.is_completed = false
     AND r.start_time <= NOW()
     AND r.end_time >= NOW()
     AND (r.max_participants IS NULL OR (SELECT COUNT(*) FROM raffle_entries WHERE raffle_id = r.id) < r.max_participants)
     AND entry_count = 0) as is_available,
    (entry_count > 0) as already_entered,
    (SELECT COUNT(*) FROM raffle_entries WHERE raffle_id = r.id) as current_participants,
    r.max_participants
  FROM raffles r
  WHERE r.id = raffle_id;
END;
$$;
